### PR TITLE
save a drawing to localStorage

### PR DESCRIPTION
**Pull request by dinok3**

### CODE REVIEW

**Comment by ErikUmble** [comment]
Nice job, dinok3. The only issue is that it does not work to resize the canvas with this updated code. I will update the resize function to remove the grid from localStorage (which will also add the functionality of clearing the canvas). Thanks again for contributing; are you fine with your name being added to the contributor's list?

**Comment by dinok3** [comment]
Thanks, Erik. It was so fun to contribute to project especially since it's
my first pull request. I was trying to find ways where it might not work
but forgot about resizing canvas.Also should an image be lost when resizing
canvas? I'm happy that my name is in contributor's list.

ned, 9. lip 2024. u 00:58 Erik ***@***.***> napisao je:

**Comment by ErikUmble** [comment]
That's a good point that people could benefit if the drawing stays when resizing the canvas. Do you think it would work to add logic to the ResetSize function to make a new grid of the new size, copy over anything possible from the localStorage grid, and assign the new one to the localStorage grid?
I'd imagine we want to simply provide a separate button, then, for clearing the canvas, which would remove the localStorage grid and reinitialize. Does that behavior sound good from your perspective?

**Comment by dinok3** [comment]
Sounds good, we can have reload button that reverts grid back to 48x32 and
clears content and resize button that resizes grid and leaves the image.

pon, 10. lip 2024. u 13:50 Erik ***@***.***> napisao je:

**Comment by ErikUmble** [comment]
Ok, that sounds good. Do you want to make those changes? If not, I can.

**Comment by dinok3** [comment]
I can do it just not until weekend, have some stuff in college...

pon, 10. lip 2024. u 23:37 Erik ***@***.***> napisao je:

**Comment by ErikUmble** [comment]
Sounds good.

**Comment by dinok3** [comment]
Do i just push changes or do you want to approve them?

uto, 11. lip 2024. u 00:44 Erik ***@***.***> napisao je:

**Comment by ErikUmble** [comment]
Either way is fine. You can push or submit pull request. I'll review either way.

**Comment by ErikUmble** [comment]
Thanks for making the changes!

**Pull request merged**
